### ISSUE TITLE
Wrong bundle definition

### ISSUE THREAD

**Issue by beatreichenbach** [ynput/ayon-dependencies-tool#17]
I just installed a couple of addons manually onto my brand new server v`1.0.3+202402081838`.

Then I ran into the issue described in this [forum post](https://community.ynput.io/t/ayon-launcher-missing-dependencies/786/6).
So next I try to create these dependency packages.
When running `./start.sh list-bundles` I get `Wrong bundle definition for Studio-Name-2024-02-22-01`.

This is because the `bundle_dict` is missing the key: `installerVersion`:
https://github.com/ynput/ayon-dependencies-tool/blob/a8a3a0a01dfad13b5d9b154289fe264420d8955f/dependencies/core.py#L157

Am I missing something?

**Comment by iLLiCiTiT** [comment]
> Am I missing something?

From the message it looks like the bundle does not have set ayon-launcher installer version.
![image](https://github.com/ynput/ayon-dependencies-tool/assets/43494761/ce648aea-62a4-4199-8961-25a8d4d79a17)

**Comment by iLLiCiTiT** [comment]
> My guess would be that in theory the dependency tool should provide installation for anything that is needed, and the bundle doesn't contain a launcher, then it should simply be ignored.

Dependencies tool does use python version from ayon-launcher on server, and final dependency package does not contain dependencies that are already in ayon-launcher, so the ayon-launcher on server is must have.

**Comment by beatreichenbach** [comment]
Copy, thank you for the information!
I'll see if I can't add all of this to documentation at some point.
