### ISSUE TITLE
Unable to properly locate python3 

### ISSUE THREAD

**Issue by ddesmond** [ynput/ayon-dependencies-tool#18]
https://github.com/ynput/ayon-dependencies-tool/blob/a8a3a0a01dfad13b5d9b154289fe264420d8955f/dependencies/core.py#L144

This line breaks doing a bundle package.
You should not rely on shutil while this may be run in an environment. 
On windows it breaks in multiple ways.

**Comment by MustafaJafar** [comment]
I was able to replicate your issue. 
More Info in my comment here https://community.ynput.io/t/ayon-dependency-tool-fails-to-build-for-bundle/1298/3

**Comment by MustafaJafar** [comment]
Hello,
I checked this again. It's advisable to use [pyenv](https://github.com/pyenv/pyenv). 

The issue you've highlighted relates to an incorrect fallback to the installed Python on Windows. This may have gone untested, as we primarily relied on `pyenv`.

Therefore, closing this issue. If the issue persists, please don't hesitate to reopen it or create another issue.
